:PROPERTIES:
:ID:       ce93e0cd-d9bb-4cc1-a910-237a1f9e3fec
:END:
#+title: Training Notes: Discover Next Steps

* Identifying the goal
Some questions that can help with identifying the goal:

- What would you say is causing you the most pain right now?
- What do you think would be helpful for us to focus on today?
- Which of the situations you've talked about today, if resolved, would have the greatest impact on how you're feeling right now?
- HWat do you see as your options right now?
- What would you want your (friend/boss/partner/etc) to understand if you were to reach out to them?
- In an ideal situation, if everything went your way, what would happen next?
- What might some relief look like for you right now?
* Discover Next Steps
** Collaboration
We aren't here to give advice or tell a texter what to do or not to do.  It's our job to work with texters to uncover what works best for them.

Typically next steps fall into one of three categories

** Coping Skills
*** Discover Current Coping Skills:
- *Start by asking texters how they're coping with their crisis up to this point*

 - Some coping skills:
   - activies
   - hobbies
   - distractions
   - self-care
 - Things they /do on their own/
 - Texters often disregard their own coping skills as not enough or are too overwhelmed to even think about their coping skills
 - The most important part of discoving coping skills is *allowing the texter to lead*

 - *Takeaway*: Asking how they've been dealing / dealt in the past reminds them they have control over their situation.
   Lead with open-ended questions to discover what coping skills would best help the texter.

**** Texters whose goal is to be heard
Many texters want simply to be heard and don't want to leave the conversation with next steps and that's ok.

It can be helpful to ask them what they plan to do after the conversation ends, that wahy we can check in without them feeling like they have to think next steps for our benefit.

*** Discover new coping skills
- If the crisis is new, texters are reaching out as the first thing they've done to manage it.
- We can explore coping skills that have brought them relief when they've felt similarly.
- We can also explore activities, hobbies, or skills they haven't yet tried and might be interested in doing.
- We *brainstorm* with them. We focus on their feelings and what has worked to manage them previously.
- It doesn't have to be specific to the crisis, but about emotions surrounding the crisis
- The most transparent approach is to directly ask if their open to brainstorming with you directly.

**** Texters who are high or imminent risk
- Working with these texters to identify coping skills they might already have or brainstorming ones is critical to helping them to get to a cool calm
- Sometimes its helpful to frame the next steps about for a way to keep them safe or reach the goal they've identified

** Social Support
- Reaching out to their social circle reminds texters they are not alone in their crisis
- In general, this is about reaching out to someone in their life they *trust* and who will *listen*
- We work to identify who they usually talk to about their issues:
  - family
  - partners
  - friends
  - therapist
  - teachers
  - colleagues
- To start we ask who the texter has shared their crisis with besides us or who they've trusted with similar information in the past.
- *Takeaway*: Not all support systems are truly supportive and we ant to be mindful of that.  Texters who know they can connect with best.
  - We want to keep our questions open-ended and *avoid making assumptions*

*** Social Distraction
- If they don't have a strong support system, they can still find benefit from being around other people, this is /social distraction/
- Simply the act of being around others
- connecting with people or visiting easy-going social settings (coffee shops, places of worship, busy parks, exercise classes, stores, etc) can provide relief from negative emotions
- Social distraction is not beneficial for *all* texters, and it's not our place to suggest it.  We can offer it as a possibility and ask how that might make them feel.

** Resources
