:PROPERTIES:
:ID:       f551aaf6-339f-4cec-8fac-47e65e9bb2e3
:END:
#+title: Step Work -- Guilt and Shame

* Guilt and Shame

Guilt -- I did something wrong.  Shame -- I am wrong.

Guilt is the feeling I feel when I've done something wrong or something I'm not proud of.  Usually, it sits like a weight on me, makes me feel heavy, burdened.  Guilt is often relieved by making things right; if I understand what I did wrong, I can ensure I don't repeat it, make amends for what I've done and move forward.  Some guilt carries a burden that a simple apology or even forgiveness can relieve.  When we do something that can't be undone, that has a lasting impact on our spirit.  It doesn't have to stop us, but the weight of the burden likely will be there.  While I can be forgiven, by others or by myself, some guilt about our past helps us to not repeat it.  We can use the pain of that guilt to help others, remind ourselves about what we've done and how important it is to not repeat the past, and live the life we won't be burdened by.

While guilt is the feeling you get when you feel you've done something wrong, shame is the feeling when you feel like *you* are wrong.  You feel like you don't deserve to be forgiven because you are so broken that you're not salvagable.  Shame isolates you and shuts you down.  You can come back from mistakes, but you can't change your deep identity. If you feel like you're *wrong* or feel like you are malformed, there's no changing your true nature.  When I'm feeling shame, I don't deserve forgiveness, because how can you forgive something that, by its very nature, is bad/evil/wrong.

I'm finding I feel a lot of residual guilt over my past enabling and pushing others to use.  When fellows go out, that's often very sad, but when someone I used with or sold to goes out, it hits me particularly hard.  This isn't centered in feeling responsible for their relapse -- I definitely am not playing an active part in their disease /now/. That said, I do know I played a part in their disease at some point.  For some, I may have pressured them into doing more than they wanted, may have lead by example in displaying how good the more extreme things I did felt. I was an example of someone without the obvious consequences who used frequently, but still had a house, a job, a car, a lot of money.   My lack of consequences was a counterpoint to every instinct to quit -- look at him, he hasn't lost everything, I don't have to either.

I did a lot of harm, and seeing my fellows continue to struggle with it is a visual reminder of that damage, even if I'm not the current cause.  I was *never* really the cause, just a contributing factor.  I work with others and be of service to use my experience to help others.  I share honestly about my struggles so others know they aren't alone.  I celebrate the good and work through the bad times in public so others can see that recovery isn't all sunshine and roses nor is it all doom and gloom.
