:PROPERTIES:
:ID:       3328c9da-d800-4c24-a882-24c1b60cedac
:END:
#+title: Step 9 - Amends - Ryan
Hi Ryan,

As you know, I'm working my program to stay sober. Today is day 81 when I'm writing this.  We had a bit of a whirlwind of a relationship and I hurt you throughout our time together.  You were right, I was using for sex and using partner.  I bragged about bagging the straight guy to as many people as would listen, and took a lot of pride in the idea that I "turned" you. Instead of treating you like a human with his own feelings, you became another notch on my bedpost that I used to stoke my ego and pride.

I never set boundaries with you, but expected you to obey them.  These unexpressed expectations are impossible to match and that just left you in a position to fail.  Throughout our time, I enabled your addiction in order to keep you coming back.  At first cheap and then free drugs so that when you needed some I knew you would call and come over and we would have a good time.  You were a pawn in my manipulation to get what I wanted for myself.   I pushed you to try new things, new drugs, steroids, just to stoke my own fetishes and so that I wouldn't be alone in my misery and addiction.

Today, I live without these behaviors whenever I can.  And when I slip back into those patterns, I correct it and make amends as soon as I can, which is what I'm trying to do here.   I work with addicts in my program so that we all can stay sober, am hoping to start sponsoring when the universe feels it's a good time for me to do that, and am active in service to my fellows.  I'm hoping to get involved with a crisis support line or something similar so that I can help those in need of finding help.  If you ever need to get help, I'll gladly go to meetings with you and help you find a recovery home.

I hope you get all the hope you need.  I'm rooting for you.
Richard
