:PROPERTIES:
:ID:       D21C1455-5914-4974-8FF5-40B88A1C33B5
:END:
#+title: Step 9 - Amends - Dylan

Dear Dylan,

This is the fifth version of this letter I have written to you.  It's been impossible to capture how I feel either due to my emotions threatening to overtake me of because, after rereading what I wrote, it was so sterilized that it lost all resemblence to what I'm thinking.   Maybe the sixth time will be the charm.

It's been almost two and a half months since we lost you. Today, I'm 78 days clean, the last time I used was the last night we spent together.  I owe my sobriety and my life to you in many ways.  My higher power brought you to me when I was at a point I could listen and no sooner and there was no later in the cards for you, which breaks my heart everyday.  In LA a few weeks ago, a workshop talked about there being a window in the cycle of addiction where we are ready to stop but before the urge to mask the negative emotions that drive our use takes over;  there are Steps out of the pit we've dug for ourselves, but someone needs to help you and you need to show some humility and accept the help.  You were that person for me, and I will never forget that.  I will always remember when you asked me if the meetings were bad or if I was bad for the meetings.  You saw to the core of me and I have no doubt you could have been an amazing sponsor for our brothers and sisters in this disease had you not left us.  In all honestly, I often think of you as my first sponsor; that was one of many reasons Chuckie seemed like a fitting choice for me -- I had lost my sponsor brother and his mother was presented to me.


