:PROPERTIES:
:ID:       a95e2cc9-8a00-4320-918a-7d19787ee3c4
:END:
#+title: Chair version of Dylan letter
Dear Dylan,

This is the sixth version of this letter I have written to you.  It's been impossible to capture how I feel either due to my emotions threatening to overtake me or because, after rereading what I wrote, it was so sterilized that it lost all resemblance to what I'm thinking.   Maybe the sixth time will be the charm.

It's been almost two and a half months since we lost you. Today, I'm 78 days clean, the last time I used was the last night we spent together.  I owe my sobriety and my life to you in many ways.  My higher power brought you to me when I was at a point I could listen and no sooner and there was no later in the cards for you, which breaks my heart everyday.  In LA a few weeks ago, a workshop talked about there being a window in the cycle of addiction where we are ready to stop but before the urge to mask the negative emotions that drive our use takes over;  there are Steps out of the pit we've dug for ourselves, but someone needs to help you and you need to show some humility and accept the help.  You were that person for me, and I will never forget that.  I will always remember when you asked me if the meetings were bad or if I was bad for the meetings.  You saw to the core of me and I have no doubt you could have been an amazing sponsor for our brothers and sisters in this disease had you not left us.  In all honestly, I often think of you as my first sponsor; that was one of many reasons Chuckie seemed like a fitting choice for me -- I lost mine and yours was presented to me.

I'm working Step Nine now and I have a lot of amends to make and most of them will be living amends.  I didn't act out of loving kindness with you.  I helped you relapse, tried to use money to buy your affection under the guise of providing help, and I had expectations for you that were both unrealistic and uncommunicated.  I pray my misguided "help" didn't make the situation for you worse than it started.  Going forward, I won't help anyone else relapse and will continue to work with other addicts to prevent others from relapsing and ensuring they know they have a home they can come back to with open arms should they go out and want to return.

I miss you everyday and it kills me that there has been no services or even an obituary for you. At first, I carried a lot of guilt and shame around your death but I have largely forgiven myself for those actions.  But I still miss my friend and brother who helped me more than even I truly know and hate the part I played in your death.  You saved my life multiple times: you helped me find CMA, my new home.  Had I been anywhere else when I found out you were gone, I would have followed on your footsteps.  Instead, I was welcomed with open arms after sharing my experience with you and met with a capacity for love I thought was impossible.  I thought to myself, I want to be like them, and I heard your voice saying "you can if you listen to them".  With that I surrendered for the first time, probably ever.  We are both Ravenclaws, and now I have a raven tattooed on my left shoulder. A bird to always remember the Bird that saved my life.

I meant what I said when I told you that I felt you had work to do in this world.  You really could have done so much more if you'd had more time. So I will do that work in your place.   Helping others, helping myself remain capable of helping others, and being grateful for the miracle of being alive are what I focus on, and I intend to keep telling your story. You can't be forever gone until you are forgotten, and I won't forget you.  I'll share the gift you gave me to as many others as I can before it's my time -- they will know about the man that saved me and they will carry the gift you gave me with them and if the universe wants it, they will share that with others.  Your legacy will continue far beyond my last breath.

I love you as a brother, Dylan. I hope you're at peace now and hope that I get the chance to see you again when it's my time.

Goodbye and thank you from the bottom of my heart,
Richard
