:PROPERTIES:
:ID:       b168acd2-98b2-4ec1-a3b2-c2106bcb1e61
:END:
#+title: Sponsoring Notes
* Step 1:

** Session 0:
*** Get to know each other
*** Assignment:
**** Write your story
- Think back to the first time we smoked week or drank a beer
- Consider all drugs, not just meth or alcohol. Remind them our program is one of complete abstenence
- Highlight times of particular pain.  Think -- was I powerless?   Was my life manageable?
** Session 1:
*** Reading
**** The doctor's opinion
**** More about alcoholism -- Chapter 3 - preread
*** Discussion:
**** What does powerlessness mean?
**** Define sacrifice.
**** What are you addicted to -- drugs, alcohol, sex, men, relationships, food, gamblin
**** Three fold nature of the disease
*** Assignment:
**** Write a list of everything in your life you are powerless over
**** What did you sacrifice for your addictions?

** Session 2:
*** Reading
**** Bill's Story (preread) -- Chapter 1
**** CMA Step 1
*** Discussion:
**** Straw man / The cycle of addiction
**** What does unmanagability mean to you?
**** Control & Enjoy -> IRD
*** Assignment:
**** How did your addictions manifest unmanagability in your life?

**** What are you two highest values?
- The two highest and critical values are preservation of your life and happiness
**** Write your own step 1 principle

** Key Question:   Are you powerless over your addictions?   Had you life become  unmanageable?   Are you done?


* Step 2:
** Session 1:
*** Reading:
**** We agnostics - Chapter 4
**** Chapter 2 (pre-read)
*** Discussion:
**** What is sanity?
**** What characterizes insanity?
**** Step 2 says "restore us to sanity." What does restore mean?
*** Assignment:
**** Think back over your using career (use the story from step 1 to help).  Where was the insanity?
- What were some of our crazy excuses to use drugs?
- What sorts of things did we do as we struggled to get by and find our next high?
- How did we think we could manage our use?  Did our use solve any of the problems we were using it for?

** Session 2:
*** Reading:
**** How it works -- Part 1 (up until step 3)
**** CMA Step 2
*** Discussion:
**** What a higher power is and isn't
**** Does he have a higher power in his life?
**** What non-spiritual higher powers have we had in our lives?
- Re-iterate:  It's not *the* power, but *a* power -- something we find we can rely on, the "God of /our/ understanding".


*** Assignment:
**** What qualities do you look for in your higher power.
    - Keep in mind: We often strive to become what we worship or admire.
**** Write your step 2 principle.
** Promises:
- As soon as a man can say that he does believe, or he is willing to believe, we
  emphatically assure him that he is on his way,  It has been repeatedly proven among us that upon this simple cornerstone a wonderfully effective structure can be build.

** Key Questions:
- Do you think your behavior has been sane?
- Do you believe you can be restored to sanity?
- Do you think you, or any single human, has the power to restore you sanity alone?



* Step 3:d
*** Reading:
**** How it works -- Chapter 5 Step 3
**** CMA Step 3
**** Read the rest of chapter 5 on your own
*** Discussion:
**** What is my conception of a higher power?  What are some other people I've talked to version of a higher power?
**** What does it mean to turn our will and our life over?
**** Third step prayer examples.  Read him mine
*** Assignment:
**** Write your own Third Step Prayer.
- Go to a safe place and read the prayer then call your sponsor
- Read it everyday for the next week.

** Promise:
- All sorts of remarkable things followed.  We had a new Employer. Being all powerful, He provided what we needed, if kept close to Him and performed His work well.  Established on such footing we became less and less interested in ourselves, our little plans and designs.  More and more we became interested in seeing what we could contribute to life.  As we felt new power flow in, as we enjoyed peace of mind, as we discovered we could face life successfully, as we became consvious of His presence, we bagan to lose our fear of today, tomorrow, or the hereafter.  We were reborn

* Step 4
** Session 1:
***  Reading:
**** CMA Step 4
*** Discussion:
**** Principles: Don't judge people by their mistakes.  What is his/her true nature and the content of their behavior?
**** Forgiveness: Indifference toward somoene that did you wrong
**** Anxiety and Excitement are the same: one is based in fear and the other in faith
*** Assignment:
**** Definitions:
- Ego
- Guilt
- Shame
- Love
- Value
- Humility

** Session 2:
*** Reading:
**** Step 4 in Big Book
*** Discussion:
**** Questions about doing your inventory
*** Assignment:
**** Complete your personal inventory

** Promise:
- Just to the extent that we do what we think He would have of us and humbly rely on him does he enable us to match calamity with serenity.

* Step 5:
** Reading:
*** CMA Step 5
** Assignment:
*** Read your inventory to me
*** My assignment:  Write out character defects
*** Go meditate on the list of character defects and re-read steps 1-5.
** Promise:
- Once we have taken this step, withholding nothing, we are delighted. We can look the world in the eye.  We can be alone at perfect peace and ease. Our fears fall from us.  We begin to feel nearness of our creator. We may have had certain spiritual beliefs, but now we begin to have a spiritual experience.  We feel we are on the broad highway, walking hand in hand with the spirit of the universe,

** Question:  Is there anything to add?

* Step 6:
** Reading
*** Step 6 & 7 in Big Book
*** CMA Step 6
** Discussion:
*** Define entirely ready
*** Discuss the list of character defects
*** How to do inventory
** Assignment:
*** Call me everynight, we will go over the defects we saw in ourself each day

* Step 7:
** Reading
*** CMA Step 7
** Discussion:
*** Define humility
** Assignment:
*** Write out each of the opposites of the character defects we identified
***
