:PROPERTIES:
:ID:       A893823C-3C4E-4E40-AFC5-3B0D450CEFC2
:END:
#+title: Step 9 - Amends - Gama
 
Hi Gama,

As part of my recovery, I've come to understand my part in our tsunami of a relationship.  I'm writing to make amends the best way I can given I am not sure how to reach you and it's not likely a good idea for my recovery to be in contact with anyone from my past life, especially if they are still using.

Throughout the relationship, I used money to try and manipulate you.  If I was worried you were going to leave, I used money to keep you.  I offered money as a gift and then tried to claim it was a loan if you wanted to leave.  I gaslit you about money and other behavior. Instead of being truthful to you, I would attack your question and use your insecurities against you.  All of this must have hurt;  had you wanted to leave, the money made it hard.  The gaslighting made you feel wrong even when you were voicing your needs.

When something happened, I was often too permissive of actions I found inappropriate and never held you accountable for your actions.  I used you throughout the relationship to feel better about myself, being with you proved I was a good top, proved I could have a hot boyfriend, and used your attractiveness to get hot guys to the house I could use to make myself feel good.   You are more than sexual object to be bartered. You are a human being with feelings and emotions and I ignored that.

These are all behaviors I have turned away from today.  I try and embrace their opposites in all my actions.  I practice honestly and openness in my relationships with all other people.  I practice generosity, which means anything given is done so without strings or expectations attached.   I work with addicts to help us all to recover and stay sober.   I'm working on joining an organization that helps people in crisis find the help they need.  I work my program everyday, pray and meditate everyday, and try and follow the path the universe has set for me with each action I take.  I truly feel I have become a new person.

I hope you are able to find whatever help you may need.   I pray for you often.

Thank you for helping me get to where I am today.

I wish you the best,
Richard
