:PROPERTIES:
:ID:       C091F80C-CC0F-40E5-A011-705B0531D05D
:END:
#+title: Step 9 - Amends - Jeremy

Hi Jeremy,

As part of my recovery, I'm come to understand my part in our tsunami of a relationship.  I'm writing to make amends the best way I can given I don't know how to reach you and it's not likely a good idea for my recovery to be in contact with anyone from my past life, especially if they are still using.

You were right when you said I was a master manipulator.  I used money and your lack of funds to control you, both to keep you from escorting and to keep you with me.   I tried to disguise this as generosity, but generosity doesn't come with strings attached.

I used you.  You made me feel hotter by being with someone who was incredibly attractive. I objectified you down to the size of your dick. I used you to feel better about myself.

When you left, I kept your belongings. Even the items that I bought were gifts and they belonged to you, but I kept them.

Today, I've found a new acceptance for myself; I don't have to use men to feel enough or feel attractive.  I try and live an honest and open life and question my motives to be sure my actions match my intent; if I have bad intent, I pray and meditate to figure out why and fix that behavior, universe willing.   I know I needed to meet you to get where I am today,  and I thank you for that.  I hope you can find any help you need one day and are able to live a fulfilling life, as well.   In exchange for the items I kept, we can call the loan you took from me for the certifications and gambling paid.   I work with addicts to keep us all sober.  I work my program everyday, I pray and meditate everyday, and I hope to sponsor other addicts when the universe feels it's time.  I am working on volunteering for a cause that helps others in times of need to help balance the scales of my past life.  I feel I'm a new person -- I'm not sure you would recognize me anymore.  I am also trying to get involved with people in crisis.  When they are victims of sexual assault, emotional stress, drug addiction, or other crises, maybe I can help them find the help they need to get into a safer place for them and help them find their way to the life they are supposed to have.

Thank you for your help in getting me to where I am today.  

I wish you the best,
Richard
