:PROPERTIES:
:ID:       d463ee11-d63f-4208-81eb-ff56ca0af512
:END:
#+title: The Steps in A Different Way
* Conditions on Sponsoring
- We are not doing this as sponsorship, we are doing this as peer equals.
- Take good notes to teach
- The essence of our relationship is to keep our word to each other that is the foundation of our relationship.
- Before you break your word, change the contract.
- At least two meetings that you commit to every week until you are done with the steps.
- Meet two new people every week that you go to
- Sit in the front row meeting until we finish the steps, this helps change your perspective, and you hear what the person is saying.
- Be open to sponsorship by the third step (not for someone who is new)

* Pre Step -
“ask the person the exact nature of your wrong” (more so for people who have already been through the steps)

- feelings ; have the person focus on the feelings.
- examples - I am not enough, I am not worthy, no one loves me,  and i’m too much..
- And allow the person to write.
- It’s usually one thing.
- Mine was I am not enough and I was seeking approval through outside sources.

*First timers through the steps*
- Also, you can ask them to write out their story, what got them here. This will tie into powerlessness and unmanageability.
- Also, you can have them write out what are their intentions with the steps, what they want to get out of them.

* Step 1

We Admitted We Were Powerless Over Alcohol and Our Lives Had Become Unmanageable.

- Read Step 1 in 12 and 12 (AA or CMA)
- Read Doctor’s Opinion, Bill’s Story, and There is a Solution
- Focus on threefolds of the disease, mental obsession, spiritual malady, and allergy
- Step 1 is on page 30 in the big book

** Questions
:PROPERTIES:
:ID:       32616f52-6216-46c8-8155-4fc73137e174
:END:

-Tell them to write out a list of everything they are powerless over and how is it causing their life unmanageability
- Define powerlessness and unmanageability.
- What are your two highest values? Example: Mine and Kimmerz are Love and Integrity
- The two absolute highest and critical values are preservation of your life and preservation of your happiness.
- Ask yourself, Does this add to my life and does it add to my happiness?
- What is your principle?
        - Enemies
        - Sacrifice- Giving up something you value for something of less value
        - Guilt- The feeling of remorse over an offense

** Definitions

- Love- is a high value or appreciation for someone or something.
- Unconditional Love- The initial goodwill, love, trust, loyalty, and respect that you give to somebody just because they are trying. Beyond that, they have to earn it.
- Emotional Prostitution- when you share intimate information with someone who hasn’t earned it.
- Boundaries- To take care or keep safe, is it a win/win situation to enter my personal space.
- Insanity- Doing the same thing over and over again, expecting different results.
- Powerlessness- lack of power, ability, and influence. It can’t be manipulated
- Unmanageability- impossible to manage

* Step 2

Came To Believe That A Power Greater Than Ourselves Could Restore Us To Sanity.

- Read step 2 in 12 and 12 and We Agnostic
- Step 2 is on pg 47 second paragraph

** Questions:
- Write a list on of what my HP is (whatever you worship, you become like)
- How do we value ourselves, just as much as our HP does?
- What is their definition of sanity
- Write your own Step 2 principle

** Second step promises:
As soon as a man can say that he does believe, or is willing to believe, we emphatically assure him that he is on his way. It has been repeatedly proven among us that upon this simple cornerstone a wonderfully effective spiritual structure can be built.” Page 47
** Definitions

- Ego- the opinion you have of yourself
- Sanity- Soundness of Mind
- Grace- Unmerited favor

* Step 3

Made A decision To Turn Our Will And Our Lives Over To The Care Of God As We Understood Him

- Read step 3 in 12 and 12 and Step 3 part in How it works

** Questions
- Write out the prayer the way it is in the Big Book
- Write out the third step prayer as an irrevocable contract, in your own words.
- Go to a safe place and read the prayer and then call your sponsor
- Am I a person of my word?
- What is your third step principle?

** Definitions
- Will and Lives- thoughts and actions
- Care Of- To have God enter your thoughts, choices, and actions, does not excuse responsibility for my thoughts, choices, and actions.

** Third Step Promise
All sorts of remarkable things followed. We had a new Employer. Being all powerful, He provided what we needed, if we kept close to Him and performed His work well. Established on such a footing we became less and less interested in ourselves, our little plans and designs. More and more we became interested in seeing what we could contribute to life. As we felt new power flow in, as we enjoyed peace of mind, as we discovered we could face life successfully, as we became conscious of His presence, we began to lose our fear of today, tomorrow or the hereafter. We were reborn." Alcoholics Anonymous p.63

* Step 4

Made A Searching And Fearless Moral Inventory Of Ourselves

Read the 4th step in 12 and 12 and the 4th step in the big book, pg 64

** Questions
 - list of columns; who (resentment), the cause, affects my, and my part - these are the 4 columns and leave the 4th one blank. 4 lists; resentment list, fears list, sex list, and guilt ( what do i feel guilty for and you just write that out)
- Write out definitions of ego, shame, and guilt.
- Write out definitions of love, value, and humility
- What is your principle?

** Definitions

- Forgiveness - no energy and I have indifference towards the person, place, or thing.
- Resentment - Me taking poison trying to hurt you. Renting space in your head and they aren’t even paying for it. Do they own me?

** 4th step promise
- “ Just to the extent that we do what we think He would have of us and humbly rely on him does he enable us to match calamity with serenity”
- “We have begun to learn tolerance, patience, and good will toward all men, even our enemies, for we look on them as sick people.”

* Step 5

Admitted To God, To Ourselves, And To Another Human Being, The Exact Nature Of Our Wrongs.

Read 5th step in the 12 and 12
** Questions
Listen to their 5th step
What is your principle?
After they finish reading step 5, they need to text their sponsor that they are ready to go onto step 6

** Step 5 promise
“Once we have taken this step, withholding nothing, we are delighted. We can look the world in the eye. We can be alone at perfect peace and ease. Our fears fall from us. We begin to feel the nearness of our creator. We may have had certain spiritual beliefs, but now we begin to have a spiritual experience. The feeling that the drink problem has disappeared will often come strongly. We feel we are on the broad highway, walking hand in hand with the spirit of the universe.”

* Step 6 & Step 7

6. Were Entirely Ready To Have God Remove All These Defects Of Character?

7. Humbly Asked Him To Remove Our Shortcomings.

Read second paragraph page 75 to the middle of page 76, and finish reading through the seventh step prayer.
Read step 6 and 7 in the 12 and 12.
I like to split up each step, but do them within a week of each other.
** Questions
What are your principles?
Step 6 question, what is the difference between a man/woman and a boy/girl?
Are you willing to accept you are not perfect and that is okay?
Step 6 - have the person write the list of all their character defects, have them focus on if they are showing up in their life.
How are my values being reflected in the world?
Step 6 - have the person write the list of all their character defects, have them focus on if they are showing up in their life.
Step 7 - have them write a list of the opposite behaviors of their character defects, humbly ask their higher power to remove them, and invite the positive behaviors into their lives.
Step 7, what is humility and why is it important to an alcoholic?
What is the difference between humility and humiliation? The difference is whether I accept the truth or not. At the core of humility is one thing, only to remain teachable.

* Step 8 & Step 9

8. Made A List Of All Persons We Have Harmed And Became Willing To Make Amends To Them All

9. Made Direct Amends To Such People Whenever Possible, Except When To Do So Would Injure Them Or Others

Read in the big book and 12 and 12 steps 8 and step 9

** Questions
3 columns
First Column- persons or institutions I have harmed
Second Column- harms that i have caused
Third Column - How intend to repair the harm
Take notice, the harms were physical, mental, or spiritual
What did you take from the Universe and What did you give back in kind?
What is your principle for Step 8 and Step 9

* Step 10

Continued To Take Personal Inventory And When We Were Wrong Promptly Admitted It

Read step 10 in big book
Read step 10 in the 12 and 12 every night for 2 weeks

** Questions
Write out the difference between reacting and responding?
Ask them to write out, When should something be said?
Something should only be said if it is kind, honest, and necessary - it must be all three.
Restraint of pen and tongue, sometimes remaining silent is the most spiritual response.
Write out two things you got out of step 10
Write out your principle

** Step 10 promise -
“and we have ceased fighting anything or anyone - even alcohol. For by this time SANITY will have returned. We will seldom be interested in liquor. If tempted, we recoil from it as if from a hot flame. We react sanely and normally, and we will find that this has happened automatically. We will see that our new attitude toward liquor has been given to us without any thought or effort on our part. It just comes! That is the miracle of it. We are not fighting it, neither are we avoiding temptation. We feel as though we have been placed in a position of neutrality – safe and protected. We have not even sworn off. Instead, the problem has been removed. It does not exist for us. We are neither cocky nor are we afraid. That is our experience. That is how we react so long as we keep in fit spiritual condition.”

* Step 11

Sought Through Prayer And Meditation To Improve Our Conscience Contact With God, Praying Only For The Knowledge Of His Will For Us And The Power To Carry That Out.

Read step 11 in big book and 12 and 12

** Questions
Every night for 2 weeks have your sponsee call you at night and answer the questions on page 86.
Write out two things you got out of step 11
Write out your principle
The gift of step 11 is to find our path and what our existence is for

** Definitions

Meditation- just a fancy word for reflection, it has many different looks and there is no right or wrong way to meditate, pg 86 has questions we ask and we can reflect on the answers daily and at any time.

* Step 12

Having Had A Spiritual Awakening, As A Result Of These Steps, We Tried To Carry The Message To Alcoholics, And To Practice These Principles In All Our Affairs.

Read out of big book and 12 and 12

** Questions
Get your principal from step 12
Pick two things you relate to in Step 12

* Post Steps
After the steps are completed ask these 12 questions.

- When can you teach?
    When you know something works through your own experience
- What is the most important job of a teacher?
    To remain teachable.
- What is the difference between meditation and prayer?
    It is listening and talking, forming perfect communication. Prayer is asking the question and meditation is seeking the answer.
- What is the difference between the musts and the suggestions?
    If we choose to, there are certain things we must do to remain sober
- What is the importance of working with another alcoholic?
    To remember where we come from and to practice the solution.
- What are the only two obligations of a sponsor?
    Guide someone through the steps and for them to become dependent on a higher power and a program that will not fail them.
- How close should you get to a sponsee?
    Only as close as you are still able to tell them the truth.
- Are there any rights and wrongs in sponsorship?
    There are no wrongs, as long as your motives are pure and connected to love and service.
- What is the purpose of an inventory?
    To be specific about the problem and to be specific about the solution.
- How many sponsors can a person have?
    One Sponsor
- How many sponsees can you have?
    As many as you want, but try to have only three working steps at a time, this way you can properly give each person your honest attention.
- When do you take steps 10-12 versus steps 1-9 over again?
    When the problem is large and you need the full effect of the steps.

* Principles

(read 2-3 principles each time you do a step or up to your discretion if a certain principle pertains to the issue or step)

This is not a program of addition, this is a program of subtraction.
If you haven’t gotten a personal principle out of the step, you haven’t done the step.
There are no contradictions in spiritual principles.
There are no contradictions in existence.
Nothing is as important until it deserves you  saying it or hearing it out loud.
Be very clear and specific about everything you talk about.
If it’s not practical, then it’s not spiritual.
AA membership never depends on money or conformity.
Honoring my value is the most important thing I can do for myself.
  Show up, let go, be your authentic self, and see what happens.
Anxiety and excitement are the same thing, the only difference is that one is fueled by fear and the other field by faith.
 It is impossible to feel resentment, anger, or hate, without its cause being fear.
Resentment and fear is someone taking our value from us.
Don’t judge people by their mistakes.
What is his or her true nature and content of their character?
Why do we have emotions? Emotions are an instantaneous energy that allows you to make a very quick evaluation of a situation, our emotions are our greatest ally.
There is a difference between Pride and False Pride, real pride is the good feeling we get from doing the right thing and/or God’s Will. False Pride is anything that keeps me away from my higher power, program, and solution.
My need to be right will ruin any relationship, it is a poison.
You no longer are allowed to chase anything or anyone for any reason, chasing is showing one or two signs of interest, after that, it becomes begging.
You are not allowed to guess anyone motives, instead look at what they actually do
Every serious thought is a prayer and every serious prayer is an action in response to that thought.
Three things most important for a life of significance; what is my purpose? Why am I alive? Am I important?
The Purpose the steps this way is to find my own value, love equals value.
