:PROPERTIES:
:ID:       AAF3CC2F-A9E7-4122-ADEE-B6212EF04C17
:END:
#+title: Step 9 - Amends - Dad
Dear Dad,

Next week, it will have been 14 years since you left us.  Jesus, it feels like it was much less time than that.  I miss you often, I wish you could have seen where I got to but I'm also glad you didn't have to see me spiral the last few years.  I'm sober 78 days today and the last few years weren't pretty.  For the first time, I have purpose beyond "proving people wrong", "making more money", or "be more well-known" and feel like I can breathe for the first time in pretty much my entire life.

I took your suicide attempts incredibly personally.  In many ways, I made them about me.  Why did you want to leave me? Why didn't you tell me how badly you were struggling?  I know now that it had nothing to do with me, but in the moment, I felt slighted and I've carried that grudge for almost a decade and a half.  When things weren't going well for me, I tended to isolate and shut out the people that cared about me and that included you.

I also saw you were struggling with your own addictions until the end, but I didn't say anything. Worse, I likely enabled your behavior by siding with you in arguments with Marlene. I agreed with her that you shouldn't be driving, but never said anything.  I saw your drug seeking behavior and just hoped it would get better.

I wish had more time.  I had a lot to learn from you still.  I carried a lot of guilt after you died;  the unreturned call from the night before you died has haunted me.  I'm not sure you ever saw me truly happy; I wish you could see me now.  I've found a new sense of peace and acceptance for myself, even if there are things still left to work on.  While I'm seeing someone and plan to marry him when it's time, I've stopped looking for a man to "fix" me. I'm not broken.  I'm not looking for anyone to make me happy; I'm that all by myself.  I'm not desperate to prove to the world that I'm not a nobody because for the first time I know that I *am* somebody.

Wait for me in the clearing at the end of the path. If Jake is there, say hi to him and keep him company.  I miss him dearly and he's got to be a little lonely.

I'm so glad you were my dad.

Love,
Ricky
