:PROPERTIES:
:ID:       71A10120-54E3-49D8-9352-C92B370FBAE8
:END:
#+title: Step 9 -  Amends - Jake
Hey my bestest boy,

I miss you so much, buddy.  Perrin and Eddie miss you a lot too.

I could have done better as a dad to you.  The last few years, I kept you locked away from me so much to keep you away from my "guests" and the meth smoke, and you hated not being able to get to me.   I didn't get to experience much of your last couple years, and I definitely wasn't a good dad to you.

You struggled when I got Perrin and I should have made sure you weren't feeling left out, but I probably just made that worst by locking you in a room with her or out of the bedroom with her.   Even the day you left us, I was high before and after the vet was here.   I wish sorry was enough to make up for losing so much time with you. And I wish you could have seen me sober again before it was your time.

I'm sober now.  I'm spoiling your sister to make sure she never feels that feeling again.  She's even made a new friend that loves her probably just as much as I do and who she loves a lot.  I work my program everyday so that I can stay clean and help others do the same.  I spend my time on worthy causes instead of chasing after sex and drugs.

I will always remember you buddy. You brought so much light into my life and saved my life more than once when I was deeply suicidial. You live on in my heart and in the hearts of JR and Gama.  They miss you a lot too.   Wait for me in the clearing at the end of the path.  My dad and Jill should be there waiting for you.  I hope you like her, she's probably a little hyper for you.  I know you never met Dylan, but maybe he's there too.  Perrin loved him, but I think he would have really loved you.  I'll see you when it's my time.

I love you so much Jake. Thank you for picking me that day at the pound.  I thought I was saving you that day, but really, the universe was making sure you were around to save me.

You really are the best dog I could have hoped to have.
Love,
Dad
