:PROPERTIES:
:ID:       46ddfb9c-d47a-423d-b07b-c5cc1e80619f
:END:
#+title: Step 9 - Amends - Marlene

Hi Marlene,

I know I've been out of contact for a while.  The reality is that I relapsed back into crystal meth in 2021 and have been deep in my addiction until the beginning of this year. I isolated myself from those that could have figured out what was going on and the people that would have voiced a concern for me; I didn't want any obstacles to keep me from using.  I'm sure that felt like I had cut you out of my life and that had to hurt.

Thoughout my adult life, I've held a lot of grudges for things I felt wronged me in the past.  I've been unwilling to put those aside and move on and that has also hurt our relationship. Instead of voicing my opinions during the few times we have spent together, I resorted to people pleasing, which just bred more grudges for me to carry around with me for not getting what I wanted. These excommunicated expectations are impossible to reach, only hurt us both, and sow disconnection.

I'm learning a new way to live now, moving on from these behaviors and embracing an open, honest, and transparent way of living. I'm working the steps rigorously with my sponsor, am hoping to sponsor when the universe feels its the right time, and try to be of service to my fellows and others in the world whenever I can.  I'm working to get involved in crisis support or another volunteer organization so that I can help others who have gone through what I went through find safety and security or just provide a compassionate word when things are dark.

What else can I do to make things right with you?

Wishing you the best,
Richard
