:PROPERTIES:
:ID:       F7E3254F-BE69-4AC2-A432-515436D9FCD3
:END:
#+title: Step 9 - Amends - JR

Dear JR,

I'm working the steps this time in recovery and I have found a solution to handle my addictions but also to help me live my life in a sober way.  As part of that, I'm on step nine, where we clean up the wreckage from our past so we can move into our new life without the carrying the weight of the past on us at the same time.

I hurt you a lot over the years.  I kept a lot of secrets from you, secrets about my using, about my sexual practices, about spying on your phone & keeping tabs on you.  When I decided I found something incriminating (which may have been completely in my mind), I would gas light you to try to get you to admit something you may or may not have even done.  When you would ask me questions I didn't want to answer, I would turn that back on your and make you feel like shit for asking.  Most of the time, the things I would accuse you of were tings I was doing myself. I held you to unfair, unachievable, and uncommunicated experiences.  When you asked about my drug use, I lied to you about what I was using.  I'm sure you didn't believe it -- who stays out for 2 days smoking pot?

Worst of all, I blamed you for my problems.  You were my biggest trigger because you made me angry because I was in so much denial about my own role in my problems and that meant the only other person in my life had to be the one that was the problem.  I blamed you for my needs not being met when I wasn't telling you what those needs were in a clear, non-aggressive way.  This culminated in me asking for a divorce in cold, compassionless way and essentially shutting you out of my life overnight.  I'm glad we've managed to stay friends afterward, it's a testiment to your capacity for love and patience.

These are all behaviors that fall outside of how I want to live my life and were all hurtful to you and to our marriage.  Saying I'm sorry isn't enough to wipe that pain away.  I try everyday to live my life without these behaviors, embracing their positive counterparts, and to walk openly and honestly through the world.  I am focusing on my sobriety and on learning as much as I can through the process.  I learn to keep myself sober but also so that I can reach out and help others like me through sharing at meetings and outside of meetings, I'm hoping to soon sponsor people if the universe feels I'm ready, and I practice acceptance daily.  Acceptance for my part in my problems, acceptance that I cannot control other people, acceptance that attachment is different than love, and acceptance that whatever happens to me, I will be OK because that's exactly what was supposed to happen to me.  I've learned a new capacity for forgiveness, patience, compassion, and humility through working the program -- all the qualities those who have loved me through my downward spiral showed to me time and time again but I left unappreciated.  Finally, I'm working to get involved with people in crisis so that I can help them find the help they need.  Maybe through these actions, I can start to write the cosmic scales to make up for the harm I've caused by trying to help others and put good energy into the universe.


What else can I do to make this right?

Thank you for being there for me.  I'm grateful to have been married to you and so very grateful to have you in my life now.

Richard
