* No title
[2022-12-14 Wed 21:46]
* No title
[2022-12-14 Wed 21:46]
* No title
[2022-12-14 Wed 21:45]
* No title
[2022-12-14 Wed 21:45]
* No title
[2022-12-14 Wed 21:39]
* Blog idea.  Switzerland of editor wars 
[2022-12-14 Wed 20:44]
* No title
[2022-12-14 Wed 21:47]
* Error: Unable to encrypt file, please check your password
[(null)]
** Note ID: (null)
* How to mock 
[2022-12-17 Sat 05:08]
* Template : tsc file should start with store function component notation
[2022-12-17 Sat 05:07]
* Druid migration
[2022-12-21 Wed 01:58]
On app open, await the max date and filters. These can be separate. Do a union all for the filters 

Dimensions to add: ads-related error all errors.
* I don’t know if I’ve ever been in love
[2022-12-20 Tue 18:12]
I realize what I thought was love is intense need to be there someone that special person in my life been nothing but addiction.

I’m at Manny again last night. It was wonderful that’s real sitting here like a fucking Martin next to me should have known him for a long time. He seems like a good guy, but you know he cheats.

And not disqualifying him for that reason God knows I fucked up, but it deserves a conversation. We haven’t had one of those we’ve had sex and I feel like I need him that’s addiction. I’ll take you to him and take you to Hell pretty people make me feel when they want me to paragraph I need to be wanted isn’t that the pinnacle of codependent I can’t be happy unless someone else wants me

And can I fix that well high on shit all the time

I can I fix it is there anyone out there for fixing it for and if I found them would I even know what was in front of me but I just been noticing a lack of addiction

Why do I help people that I need it I needed and wanted reality is trying to buy their love. I’ve known that all along. I’m pathetic
* Packages 
[2022-12-20 Tue 03:12]
Evil mode
Which key 
Projectile 
Perspective
* We need to track the oil change filter selected for the field key selectors so I don’t want people to have multiple drop-downs. That’s combine since we’re not allowing and in or out logic ones so the face component needs the track is visible for each filter they probably also need to track the order that they were selected in overall in order.
[2022-12-19 Mon 11:39]
This is like a great method. It’s overkill for what I’m doing right now I’m just going to add a filter for each of the filters and I think Harbor major category will just fall in the hardware category as a grouping who is the same thing for failure you 

Really nice to get through to work because right now I’m already getting cases we’re having to re-aggregate paper log log
* For the appearing filters, I think I was considering doing it was harder than it has to be really what we want is pieces and filters for each of the filters or presentation groups reach the filters and then their CSS not visible at first and then when they’re selected, the filter becomes visible is not quite right.
[2022-12-19 Mon 11:35]
Because that means I have a new field key selector shown but we don’t know if he’ll be next to us because yes, I ordered to the nearest generic filters yet.

Face case one select key filter with a filter value filter next to it hidden and have it visible when the filter filter chooses something so I can change

Nuisanc
* Add dash 
[2022-12-25 Sun 14:42]
-fix subtitle  
Make. Unique for share and count subtitle -/ title 
Trend metric selector
- impacted esn as second trend plot?
Maybe as secondary to failure  trend 
- app icon and app title 

After 
- migrate to separate projects. (Mono repo?
- tag code with excessive Amy’s- 
- move to data context 
- shared trend. Chart shared extent
-highlight mode through shared context. Hover sets a state variable. All charts use that to highlight the associated object and grey out the others
- make sure to clear out hover when nothing hovered 
- click preserves it.  And sets drill down state 

- cab file 
- save to image 
- chart styling to comply with dark mode 
- dark mode toggle
* 
[2022-12-22 Thu 14:41]
Who says it has to be in node
- spin up a local react app
- plot with vizkit 
- don’t even need a real rest client can use curl probably
* What plotting packages are available in node 
[2022-12-22 Thu 14:39]
* Query tool 
[2022-12-22 Thu 14:37]
It should: translate a query to arguments 

Send arguments to rest endpoint 

Display results 


Template: 

Select
${queryRows.join(“,”)
From
${tablename} 
Where 
${whereRows.join(“And”)}


Repeat for having, orderby, groupby limit 

Bonus points for Piping to plotting library
* More things for config 
[2022-12-22 Thu 14:31]
Magit 
Snippets
Translate viscose snippets
Tramp
