

* 2022
** 2022-12 December

*** 2022-12-11 Sunday
*** 2022-12-20 Tuesday:
**** Random thought from today that stood out
***** I don’t know if I’ve ever been in love
[2022-12-20 Tue 18:12]
I realize what I thought was love is intense need to be there someone that special person in my life been nothing but addiction.

I met Manny again last night. It was wonderful.  He seems like a good guy, but you know he cheats. And yet I'm obsessing over him. I can't stop thinking about the next time. I want him. I want that look in his eyes when he looks at me.

And not disqualifying him for the cheating. God knows I fucked up, but it deserves a conversation. We haven’t had one of those we’ve only had sex and I feel like I need him. That’s addiction. I can't be happy unless someone wants me. And the hotter they are, the better I feel.  Will I ever be satisified?

And can I fix that when high on shit all the time?

Can I fix it? Is there anyone out there for fixing it for?  If I found them would I even know what was in front of me?

Why do I help people?  I need to feel wanted.  So I buy them. I give them things and hope they need me because if they need me they won't leave me.  Except... how well has that been working?  The worst part is, I know I'm buying their love. I've always known that.  I used that. Jeremy was right about me.  I am pathetic.

*** 2022-12-21 Wednesday:

#  LocalWords:  Manny
