

* 2022
** 2022-12 December

*** 2022-12-11 Sunday
*** 2022-12-20 Tuesday:
**** Random thought from today that stood out
***** I don’t know if I’ve ever been in love
[2022-12-20 Tue 18:12]
I realize what I thought was love is intense need to be there someone that special person in my life been nothing but addiction.

I met Manny again last night. It was wonderful.  He seems like a good guy, but you know he cheats. And yet I'm obsessing over him. I can't stop thinking about the next time. I want him. I want that look in his eyes when he looks at me.

And not disqualifying him for the cheating. God knows I fucked up, but it deserves a conversation. We haven’t had one of those we’ve only had sex and I feel like I need him. That’s addiction. I can't be happy unless someone wants me. And the hotter they are, the better I feel.  Will I ever be satisified?

And can I fix that when high on shit all the time?

Can I fix it? Is there anyone out there for fixing it for?  If I found them would I even know what was in front of me?

Why do I help people?  I need to feel wanted.  So I buy them. I give them things and hope they need me because if they need me they won't leave me.  Except... how well has that been working?  The worst part is, I know I'm buying their love. I've always known that.  I used that. Jeremy was right about me.  I am pathetic.

*** 2022-12-21 Wednesday:

#  LocalWords:  Manny

* 2023
** 2023-03 March
*** 2023-03-24 Friday

**** 08:48 AM - Journal                                             :journal:
:LOGBOOK:
CLOCK: [2023-03-24 Fri 08:48]--[2023-03-24 Fri 09:13] =>  0:25
:END:


We are in LA for CMALA today. So far, it's been uneventful, but last night when we arrived, I did check Rent.men to check for Jeremy and he's close.  That sent me into a bit of a panic spiral, but meditating on it helped.  The reality is if he shows up there's nothing I can do.  Had I not saw him on the app, I would have still panicced, so checking obsessively isn't helping.

I also checked grindr last night on Chuckie's phone for him and had a moment of lust.  Seeing all the guys brought back some memories for me.  I didn't want to act on them, but I missed part of that lifestyle. But 1.) empty is gross and 2.) I have all that I need already.  Those facts kept me from wanting to do anything about it.

I'm antsy for steps 6 and 7. I'm ready and the weight of 4 and 5 are heavy on me.  But I practice surrender and wait.  When it's time, it's time. Instead, I reflect on what the added time gives to me.  Understanding the /entirely ready/ part, to be ready to remove all my defects and not cling onto one because I think it serves me. If my HP thinks one does, he won't take it away. If I think one does and cling on, I'm holding onto the same behaviors and thinking patterns to brought me to my knees.

So what are some opposites?  When I'm often self-centered, I'll instead volunteer today and spend my time helping the convention get set up.  Where I once was often unfaithful, I choose loyalty and gratitude for the beautiful realtionship I have now and the man who loves me dearly and who I love more than anything else in the world.  Instead of insecurity, I try and be comfortable in my skin.  I voice my feelings and needs, I don't play chess with humans to get my way. I am not in control.
