
 QoEDash
**   V2
*** Deploy and Build
- seems like a lot of the issues that I'm having are due to the typescript conversion.   Ensure that all scripts are calling the correct files (ts not js)
- To try: drop the bionic image and see if the libgc version of node 18+ will compile there
**** [ ] The datepicker doesn't close on external mouse click
:PROPERTIES:
:ID:       06b04ed0-d3f8-4036-a859-021abc9f9388
:END:
**** [ ] Need xlabel on bar chart
:PROPERTIES:
:ID:       d328e966-6543-41ce-900c-e8b15322c2d4
:END:
**** [ ] Add the FitlerSentence back
:PROPERTIES:
:ID:       70515488-6c5c-4ba9-a978-4bf6e261ad2c
:END:

**** TODO Fonts in presentation mode are often too small
:PROPERTIES:
:CREATED: [2022-12-10 Sat]
:ID:       e2aa4365-947f-40b8-b2ef-5f40d60f98fe
:END:

**** Line charts look great in presentation mode = Olid
:PROPERTIES:
:CREATED: [2022-12-10 Sat]
:END:

**** TODO Make the legend scale with presentation mode
:PROPERTIES:
:CREATED: [2022-12-10 Sat]
:ID:       9b1221ac-a85a-414f-8ff7-c46986993e03
:END:

**** TODO QoEDash validation on the PQS Smoothing does funky thigns when tyring to enter 1 
:PROPERTIES:
:CREATED: [2022-12-11 Sun]
:ID:       c75edc58-742e-49e1-9ff0-d102868969b8
:END:

**** Qoedash startup issues
*****  While the build starts the server, it doesn't actually use the build for the website.  Looking at the directory, the build directory is not present. I don't know if this is expected (and we should be running a local build) or it should be getting this from the artifactory.
***** Running npm run build seems to generate the files we need.
***** For now, I'm going to add =npm run build= to the start.sh script
**** TODO Make the legend scale with presentation mode
:PROPERTIES:
:CREATED: [2022-12-10 Sat]
:ID:       c7cd930b-b651-4637-9635-165a7d431e8f
:END:

**** TODO QoEDash validation on the PQS Smoothing does funky thigns when tyring to enter 1 
:PROPERTIES:
:CREATED: [2022-12-11 Sun]
:ID:       95c26172-edb0-4134-ba5e-b50acfaa9375
:END:

**** Qoedash startup issues
*****  While the build starts the server, it doesn't actually use the build for the website.  Looking at the directory, the build directory is not present. I don't know if this is expected (and we should be running a local build) or it should be getting this from the artifactory.
***** Running npm run build seems to generate the files we need.
***** For now, I'm going to add =npm run build= to the start.sh script
**** TODO Fonts in presentation mode are often too small
:PROPERTIES:
:CREATED: [2022-12-10 Sat]
:ID:       6850118b-9017-4272-bef8-8c088910a03a
:END:

**** Line charts look great in presentation mode = Olid
:PROPERTIES:
:CREATED: [2022-12-10 Sat]
:END:

**** TODO Make the legend scale with presentation mode
:PROPERTIES:
:CREATED: [2022-12-10 Sat]
:ID:       30fbf47c-8be4-4aaa-88fe-9417c669918a
:END:

**** TODO QoEDash validation on the PQS Smoothing does funky thigns when tyring to enter 1 
:PROPERTIES:
:CREATED: [2022-12-11 Sun]
:ID:       a87f72a4-bdae-4fe9-8248-a71f2a9a8e12
:END:

**** Qoedash startup issues
*****  While the build starts the server, it doesn't actually use the build for the website.  Looking at the directory, the build directory is not present. I don't know if this is expected (and we should be running a local build) or it should be getting this from the artifactory.
***** Running npm run build seems to generate the files we need.
***** For now, I'm going to add =npm run build= to the start.sh script
***   New Tests:
+ [ ] Date Checker unit test
+ [ ] Unit tests for as many atomic units in the UI as possible
+ [ ] Add both to cypress e2e tests as well
+ [ ] Unit tests and e2e tests for color selection
***   [ ]  TODO text on the treemap is very hard to read
:PROPERTIES:
:ID:       a18687f7-f60b-41be-8597-48eeac64ffd2
:END:
***   [ ] TODO Add item selection to the ranking filter sentence
:PROPERTIES:
:ID:       5c78a3a2-99b0-4c34-830c-8a2599b84357
:END:
**  Requests
*** Request: Look at how Dex handles multiple breakdowns
- TODO: DEX has a new feature that allows a multi breakdown approach on a curated list of dimension. This lets the user look at how say hailstorm compares to a subset of devices.  If this is logic that we can reuse,  we should add it to QoEDash
*** Request: Custom chart constructor
- From oli
- PEMs are largely wanting to be able to see how two cohorts compoare to each other or how two metric co-evolve over time.  One way to let them explore this would be to offer a configuration for two separate charts (with potentially separate
  filter values, plotparams, etc) then we overlap these two charts on top of each other
- coming up with a way to deal with the two separate states will be hardest, we almost need to create a local-only version of the state for this.*
**  Hawkins migration
+ [ ] Filter Sentences
+ [ ] summary cards
+ [ ] filter selectors/drawer
+ [ ] integrate alerts with a badge system
+ [ ] convert all tooltips to hawksins
