* PQS

** Status:



**  Activity:
***   [#B] PQS Data Quality Issue :PQS:URGENT:DataQuality:
SCHEDULED: <2022-12-07 Wed>
:PROPERTIES:
:ID:       2af8f38b-ca16-46d1-8d11-474710c106d2
:END:
 Robert discovered that there is a discrepancy in total session counts between =dse.product_quality_score_sum= and =rpt.product_quality_score_report_sum=. It looks like, after a cursory look, that there are some sessions that are being dropped from the report table.  This may be due to an INNER join between pqs and the topASN table. This means a fairly high chunk of the sessions may be being dropped. This needs a fix.

***** DONE Verify that the ASN join is the cause of the discrepancy.
***** DONE After changing, push the new workflow to prod to catch new data as quickly as possible.
***** DONE Create a backfill job that runs until the beginning of ASN addition to the data to correct the report table in Hive and Druid.
***** [ ] Run the backfill and ensure it finishes.<2022-12-08 Tue 10:10>
:PROPERTIES:
:ID:       7a17e2ed-608e-4c6d-bfcd-0e908da7bb6a
:END:
