:PROPERTIES:
:ID:       dc48b759-6b4d-4980-be76-73e37bd8f3db
:END:
#+title: Motion - Safety Card

*Tradition Five states*: Each group has but one primary purpose -- to carry its message to the addict who still suffers.

Any person seeking help with drug addiction is welcome in this group.  No CMA entity determines an individual's membership in Crystal Meth Anonymous.  It is this groups conscience that if any person endangers another individual or disrupts the group's efforts to carry CMA's message, the group may ask that person to leave the meeting.

This group strives to safeguard the anonymity of CMA members and attendees; however, keep in mind that anonymity in CMA is not a cloak for unsafe and illegal behavior.   Addressing such behavior and/or contacting the proper authorities when appropriate does not go against any CMA Traditions and is meant to sure the safety of all in attendance.

The short form of Tradition One states: "Our common welfare should come first; personal recovery depends on CMA unity."  Recognizing the importance of group unity, our group strives to create a safe meeting environment in which addicts can focus o:w
n achieving sobriety."




Original Language:

*Tradition Five states:* Each group has but one primary purpose -- to carry its message to the alcoholic who still suffers.

Any person seeking help with a drinking problem is welcome in this group. No A.A. entity determines an individual's membershiups in Alcholics Anonymous.  It is this groups conscience that if any person endagers another individual or distrupts the group's efforts to carry A.A.'s message,the group may ask that person to leave the meeting.

This group strives to safeguard the anonymity of A.A. members and attendees; however, keep in mind that anonymity in A.A. is not a cloak for unsafe illegal behavior. Addressing such behavior and/or contacting the propert authoritities when appropriate, does not go against any A.A. Traditions and is meant to ensure the safety of all in attendence.

The short form of Traidition One states: "Our common welfare should come first; personal recovery depends upon A.A. unity." Recognizing the important of group unity, our group strives to create a safe meeting environment in which alcholics can focus on acheiving sobriety.
