:PROPERTIES:
:ID:       dc48b759-6b4d-4980-be76-73e37bd8f3db
:END:
#+title: Motion - Safety Card

*Tradition Five states*: Each group has but one primary purpose -- to carry its message to the addict who still suffers.

Any person seeking help with drug addiction is welcome in this group.  No CMA entity determines an individual's membership in Crystal Meth Anonymous.  It is this groups conscience that if any person endangers another individual or disrupts the group's efforts to carry CMA's messsge, the group may ask that person to leave the meeting.

This group strives to safeguard the anonymity of CMA members and attendees; however, keep in mind that anonimity in CMA is not a cloak for unsafe and illegal behavior.   Addressing such behavior and/or contacting the proper authorities when appropriate does not go against any CMA Traditions and is meant to sure the safety of all in attendence.

The short form of Tradition One states: "Our common welfare should coe first; personal recovery depends on CMA unity."  Recognizing the importance of group unity, our group strives to create a safe meeting envionment in which addicts can focus o:w
n achieving sobriety."

"
