:PROPERTIES:
:ID:       7B695D0E-BB3F-41E4-B994-29ECF57964F2
:END:
#+title: Step Work Notes
#+filetags: Project

* Goals

Work through the 12 steps to stay sober



* First Cycle of Steps
**Sponsor**: Chuckie
**Start Date**: 2023-01-28
**Clean Date**: 2023-01-18

** [[Step 1]]: 
*** We admitted that we were powerless over crystal meth and our lives had become unmanageable

Assignment:
Write out the things I am powerless over. 

Dylan's Death
Guilt around his death and relapse
Sex
Manny
Ryan
Meth
How others see me
expectations other have for me
Food/over controlled eating/binging
Mental health problems
who wants me
what people want from me



** [[Step 2]]:
*** Came to believe that a power greater than ourselves could restore us to sanity.

Assignment:
Write out the sane response to the things I was powerless over.

Meth: Don't use Meth
Sex: Have sex with people who you decide deserve to have sex with and you want to connect with intimately.
Guilt: Make amends as needed, admit when you are wrong, forgive yourself & strive to not repeat past mistakes
Ryan: Cut him out. sober life has no place for your former slam partner.
Manny: Take inventory of your feeling. Back up if needed or if you are seeing validation or affirmation. Go Slow. Have boundaries and respect them.
Others View of me: Fuck them. Not Literally. You know you are blessed with a great job, financially secure, are attractive and internally you care deeply. You're a good friend and person


** [[Step 3]]:
*** Made a decision to turn our will and our lives over to the care of a God of our understanding

Assignment:
Qualities of my higher power & a 3rd step prayer.

Forgiving
Compassionate
Ordered in the Chaos
Loving 
Empathetic
Selfless
Strong
Vulnerable
Honest

Prayer:
I have played God for far too long.  I've tried to dominate the uncontrollable and conquer the unmanageable.

Today, I choose surrender. Help me see my path and give me the courage to follow it even when I can't know where it leads.

Give me the power to do what's right, to help myself and to hold my hand out to others. Help us stay free, remain humble, and be forever grateful.

Help free from the bondage of self. Le me be of service. Please take my ego, my pride, my fear, and help me remember my work. Help make me a vessel of hope & healing for myself and my family in recovery and those still lost.


** [[Step 4]]:
*** Made a searching and a fearless moral inventory of ourselves

Assignment 1: 
Definitions of ego, guilt, shame, love, value, humility.

Ego: Overinflated feeling of pride or your superiority to others.
Guilt: Feeling that comes when you do something wrong.
Shame: Feeling that comes when you feel *you* are wrong.

Love: Intense feeling of deep affection
Value: Principles or standards of behavior; one's judgement of what's important
Humility: Freedom from pride or ambition

Assignment 2:
Principles: Don't judge people by their mistakes. What is his or her true nature and content of their character?
Forgivness: Indifference toward someone who did you wrong

[[Step 4 Moral Inventory Notes]]
[[https://docs.google.com/spreadsheets/d/1dBph_nn4G4u60XJ4af9GYsNTuSGRcT9SgzSOUD-ojt0/edit*gid=0|Step 4 Cycle 1]]i

Ideals or a partner:
- Honest
- Compassionate
- Patient
- Makes me a priority
- Nonjudgemental
- Kind
- Sexual Chemistry & Complimentary Drive
- Common Interests
- Gentle & Loving Touch
- Level-headed
- Independant
- Communication Skills
- Receptive
- Generous
- Impeccable in his word
- Comforting
- Respects my sobriety & recovery program and commitments
- Takes delight in others' joy
- Financially indepedent


** [[Step 5]]:
*** Admitted to God, to ourselves, and to another human being the exact nature of our wrongs

In this step we share our step 4 inventory with our sponsor.

** [[Step 6]]: 
*** Were entirely ready to have God remove all of these defects of character

In this step, our sponsor helps us come up with a list of character defects.  We spend several days reflecting on this last and check in each day on how we have strayed from our character defects.

We also reflect and ask if we are /entirely/ ready to have them /all/ removed from us.

My character defects:
- judgemental
- lack of empathy
- unrealistic or unexpressed expectations
- not assertive with needs
- lying
- codependance
- self-centered
- holding grudge
- manipulative
- denial
- sex as power
- keeping stuff
- unfaithful
- using people
- gaslighting
- pusher
- inconsiderate
- stalker
- lust
- deflection
- ego
- jealous
- insecure
- perfectionist
- not asking for help
- pride
- self-deception
- future or past tripping

** [[Step 7]]:
*** Humbly asked God to remove our shortcomings

** [[Step 8]]:
*** Made a list of all person we had harmed and became willing to make amends to them all

** [[Step 9]]:
*** Made direct amends to such people whenever possible, except when to do so would injure them or others.

** [[Step 10]]:
*** Continued to take personal inventory and when we were wrong promptly admitted it

** [[Step 11]]:
*** Sought through prayer and meditation to imporve our conscous contact with a God of our understanding praying only for the knowledge of God's will for us and the power to carry that out

** [[Step 12]]:
*** Having had a spiritual awakening as a result of these steps, we tried to carry this message to crystal meth adicts and to practice these principles in all of our affairs


* Related Topics:
[[Recovery]]
[[Crystal Meth Anonymous]]
[[Addiction]]

