:PROPERTIES:
:ID:       C2AAFDD6-31A1-442B-9ACF-1CAA9CF95A1C
:END:
#+title: Step 4 Moral Inventory Notes
* Resentments

Notes from the CMA 12 Steps:  The Twelve Steps for Crystal Meth Addicts

*# Who:
"We start by putting down the names of everyone we believe has hurt us."   
"We try and include only the people we truly resent."

Resent means to feel again, so we are not interested in conflicts where the unpleasant feelings we have about it have long passed.  They encourage using the elevator test.  If elevator doors opened in front of us and the person in question stepped off, how would we react?  If this is a nasty surprise and we're not sure what to say, they belong on the list.

If there are people that arouse feelings we can't describe, we should include them and our sponsor can help us figure it out as we go along.

**If anyone or anything has hurt us, it belongs on our list**

*# What?
In this column, we describe how each of the people from the first column hurt us.  

*# Where?
Where did we feel the hurt?  Which instinct was wounded?
"It's interesting to think of our conflicts in these terms: how our needs and desires have been blocked. We consider the instincts that felt threatened and write them down."

*# My part
"Where have we been selfish or self-seeking? When were we dishonest or inconsiderate? What fears drove our reactions?"


* Fears

*# What Fears?
Write out a finite list of fears that drive our character defects.  Thinking about the main areas of our life, finances, and careers, romances and friendships, family and self, we ask some questions.  Are we afraid of being poor or overlooked or having too much responsibility and success?  Are we frightened of intimate or being alone?  When it comes to ourselves, are we afraid of being demeaned by others?  Or having people find out about some not-so-great thing we did?

*# Triggers
For each fear, what triggers it?  What part of our life feels threatened?

*# Belief
What is the belief that is driving the fear?  What story did we tell ourselves -- that we now believe wholeheartedly -- that brings the fear out the moment we get a hint of confirmation?


* Assets
What assets to we bring to the table?  
One approach: look at our most glaring character defects and name their opposites and find instances where we practiced those qualities.
Another approach:  Take the 12 most persistent character defects and list two assets for each one.

* Sexual Inventory
First look over the the love and sex relationships we've included in our inventory.  Note times when we let people treat us poorly and times when we could have behaved better.  Next, we look at other encounters.  Experiences where we didn't feel resentment but left us feeling uncomfortable just the same.  Ask: Where were we selfish, dishonest, or inconsiderate?  When did we unjustifiably arouse jealousy, suspicion, or bitterness?  Have we been hurtful or abusive to anyone?  Have we objectified partners, reducing them to their attributes and overlooking their humanity?  We have we allowed them to dehumanize us?  Did we walk into situations where we knew we'd get hurt?    What fears drove these?


* Related areas:
