:PROPERTIES:
:ID:       0B20BFE2-5ED2-4211-9AB3-E1ADB1570E57
:END:
#+title: The Twelve Steps for Crystal Meth Addicts - Book

Book Notes
Title: The Twelve Steps for Crystal Meth Addicts
Version: Pre-release version, not fit for print or distribution

* Highlights
** Step 1:
- We call this reaching a spiritual bottom. Without reaching one, we would have kept cycling through relapse after relapse, enduring astonishing agonies.
  page 13

- We knew our addiction was progressive; it was only getting worse and worse. And we realized, at least intellectually, that it could one day be fatal.
  page 13

- Many of use made the mistake of thinking we could keep on using because we didn't look so hopeless on the outside. But it wasn't about our outsides, it was about how hopeless we felt inside.
  Page 13

- In Step One, we made an honest catalog of our misery. We shined a light on all the reasons we had to quite doing drugs and admitted all of it to ourselves
  Page 14

- So what was the whole story? What happened to us? Most of the time, our sponsors asked us to write it all out.  We thought all the way back to the first time we smoked weed or had a beer.
  Page 14

- You'll hear a lot about powerlessness and unmanageability as you get sober. Recognizing both in your life is key to accepting you're an addict -- and starting to recover.
  Page 14

- This is what we mean by powerlessness. Needing to stop, vowing to stop, and not being able to.
  Page 14

- Out willpower was utterly useless. Crystal meth was much more powerful than we were. We couldn't control it.
  Page 14

- This is the most insidious thing about our disease: At some point, we were unable to stop; something mysterious took control of us. Over and over, we'd tell ourselves that this time would be different. Yet over and over, this time was only worse than the time before. And over an over, knowing that more pain awaited, we used again anyway.
  Page 15

- But that adventurous spirit started long before. It's not that alcohol, marijuana, and poppers are gateways drugs; we're just the sort of people who love running through gates.
  page 15

- Our fellows called it the ABCs: "Alcohol becomes cyrstal"
  page 15

- But ultimately our issue was addiction, not any particular chemical. That's why we learned to say "a drug is a drug is a drug." Some people may be able to use other drugs, but we couldn't.
  Page 15

- A grim truth dawned on us.  We thought we used because of all the horrible stuff that happened to us. In face, horrible stuff kept happening to use because we used. Every story is different.  There is no set checklist of unmanagability.  Each of us leaves our own unique trail of disasters behind us.  We'll all born with a different tolerance for suffering, but suffer we do, each in our own way,
  Page 16

- And that usually means we start writing.  Some addicts got it down in a narrative. Others go through a workbook, answering focused questions.  The main thing is to put down on paper the central facts of our story.
  Page 16

- Addicts have a built in forgetter so we need to make a very speicifc movie we can play whenever we feel triggered to use.  Living in Step One, we have the film ready to roll all the time, so we can answer any craving with a resounding "not today".
  Page 17

- We needed concrete, working definitions of these ideas, based on our experience: What did powerlessness and unmanageabilty mean to us?  And how exactly, had we gone insane?  Not jiust the paranoia, the hallucinations, the psychosis so many of us experienced.  Could we see that our day-to-dat choices in active addiction were just bonkers?
  Page 17

- Our fellows tell us this is the only step we have to work perfectly; if the day comes when we forget our powerlessness and unmanageability, we're likely to pick up.
  Page 17

- We don't reserve a place for them in our fantasy life or future "what ifs" or leave a back door open by maintaining relationships with people we used with.  Keep crystal in our life would be delusional; thinking we have any power over it almost ensures we'll go back to using.
  Page 17

** Step 2:
- But even those of use who are religious have a "God problem" -- we've been playing God in our own tiny hells.
  page 20

- Focus on just staying vlean, they said, and let the program itself be your Higher Power.  Our HP could be GOD -- the group of drug addicts who were helping stay away from meth a day at a time.  Or it might be the good orderly direction we were learning from them.  Maybe it was the gift of desperation which week by week was becomimg the gift of dignity.
  page 18

- Step two doesn't promise we will become sane again.  The program isn't magic -- there will be plenty of days when our emotions get the better of us.
  Page 18

- We've put down the drug, but can't change our thinking pattern so easily.  It can be tough to live in thee acceptance of step one and stick to the commitment not to pick up when our moods keep swinging so wildly and our thoughts are racing around the clock.
  page 18

- Addicts like to say that insanity is "doing the same thing over and over expecting a diffferent result".  Time and again, knowing we'd end up in the same sad mess, we picked up crystal.
  Page 19

- "This time will be different" we said knowing in our hearts that this time was be absolutely the same or possibly worse.
  page 19

- Step two doesn't say that we'll become sane for the first time, but that our sanity can be restored. Knowing this helps us discard our old attitude of victimhood.
  Page 20

- Guiding us through this step, our sponsors ask us to think back over our active addiction. In truth, we were insane long before we used; the problem, as our friends in AA say, was "the thinking that preceeded the drinking".  What were some of our crazy excuses to use drugs?  What sorts of things did we do as we struggled to get by and find our next high? We knew what would happen every time we picked up but did it anyway.  Life became a complete calamity, yet we were still sure we know how best to handle our problem.
  Page 19

- To bring this point home, our sponsors might ask us to seek out people we relate to and ask them to tell us about their HP. For some that power is the God they grew up with. For others, its the majesty of science, the inspiring genius of a pop diva, the spirit of a dead grandparent, the wind whispering in the trees, or the circle of recovering addicts in their home group.
  Page 20

- So when our sponsors tell us not to stress out about finding a HP, they mean it.  Only keep an open mind, they say. Our growing faith in the program and the time we spend pursuing the Good Orderly Direction of the steps will naturally lead us to deeper reflection on the question
  page 21

- It's not *the* power but *a* power -- something we find we can rely on, the "God of *our* understanding" described in the rest of the steps.  Our relation with it isn't fixed; it will change as we change.
  Page 21

- Religious people, asking for concrete help from the God of their undarstaning, feel their convinctions deepen ... Agnostic people, on the other hand, often become more passionately so. They go deeper into the mystery of the Universe; not knowing for them is the whole beautiful point; any god they could thoroughly comprehend just wouldn't be powerful enough.  Athiests find their own sublime spirituality, drawing power from their ancestors and heroes, or from astral mechanics, or the changing of the seasons, or the mighty rhythm of the pounding surf
  Page 21

** Step 3

- Given the magnitude of the job, the authors of the twelve steps offered us a brilliant and beautifully honest caveat.  They didn't write "Turned out will and our lives ..." No. Just "*Made a decision* to turn our will and our lives over..."  No one who's ever lived has always been in total concert with the rhythm of the universe.
  Page 22


** Step 4:
- Falling prey to self-sufficiency or isolation, we may eventually deny the truth and use again.  That's where Steps Two and Three come in. They give us a new spiritual focus, a plan, and a network of like-minded people we can count on.  We're no longer alone with our problem.
  page 26

- What we're making is a truth inventory.
  page 27

- When we've tried to get sober before, we were often driven by shame or remorse about the thing's we'd done.  It didn't work; guilt by itself is truly a wasted emotion. What if we could unlearn the behaviors that caused the remorse in the first place?
  page 27

- Addiction is that rare illness that can be arrested if we treat the symptoms, in this case our warped behaviors.
  page 27

- When the work is challenging, we remember what our fellows have said: Like everything else in the Steps, this is the way for us to find freedom.
  page 27

- And though we might not have had a part in the incident, we always have a part in the resentment about it. When it comes to events that are far in the past or otherwise abstract, continuing to nurse the grudge is entirely on us.
  page 29

- We call these character defects or shortcomings, but a lot of us find it more useful to think of them as defense mechanisms or negative reactions.  How do we behave when we feel *cornered*?
  page 29

- Most of our fears, it turns out, are overblown. They're lies we've told ourselves to explain our flawed understanding of life.
  page 30

- A lot of us resist writing about our assets, much less talking about them. We don't mind telling people what a piece of shit we are, but looking someone in the eye and saying we're kind or funny or loving is impossible.  But an honest inventory requires listing everything -- the bad and the good.  We need to remember why we're worth saving.
  Page 32

** Step 5
- We're leading someone into the dark, dusty corners of our past, and pointing out all the clutter we've hidden away.
  page 35

** Step 6
- Not surprisingly, most of us end the inventory feeling a bit preoccupied with our exes, old bosses, former freinds.

- Whatever the thing was -- cheating, stealing, lying, avoiding, disparaging -- we need to be sure we aren't going to do it again.  Once more, we're reminded that the Steps come in order for a reason: We're building a house;  each brick rests on the one below it.

- But the character defects we've uncovered do not belong in the past. Maladapted as they are, they've become our instinctual defenses, the way we react when we're threatened or cornered.

- Don N, had a salty way of summing up recovery: "Quit doing drugs and stop being an asshole."

- My now, most of us have powerful evidence that our obsession to use can be lifted, but as for all of our /other/ problems? The fears and character defects that keep us in conflict with the world can continue to torment us for a long, long time.

- Some say Six and Seven are where we really begin to grow up.  Looking back over the inventory we shared with our sponsor, we might note that we have a history of angry outburst or rash correspondence ..., we're more comfortable objectifying anonymous sex partners. ... Whatever our shortcomings are, they won't magically vanish.   They may be warped and destructive, but they're part of us. It feels unnatural on a gut level to let them go.

- Many of us prefer to call these traits character defenses instead of defects -- we needed them to survive.   If we never take ny risks, we'll never get rejected. If we're often angry, people will learn to stay out of our way.  If we're devious and manipulative, we may indeed get the things we thing we want from people.  And if we never care to look at these things, so what?  We find a strange comfort trapped in the hypnotic grasp of self-pity.

- Many of us take that specific list and, with our sponsor's help, write out their opposites.  Could we be gengle instead of aggressive? Humble vs. conceited? Confident vs. insecure? Diligent vs. lazy?  Faithful vs disloyal? In our prayers and meditations, we ask are we willing to stop doing X, Y, and Z?  Are willing to try A, B, and C instead?

- To help us along, our sponsors might ask us to notice throughout the day when we're feeling uset or uncomfortable and identify whatever character defects are flaring up.  ... Our shortcomings always appear when we are operating on instincts.

- Knowing we're often going to be confused about our impulses, out sponsors teach us to practice "restraint of tongue and pen." If we feel a powerful urg to write or say something, we ask outselves three questions: Does whatever it is need to be said?  Does it need to be said by me? Does it need to be said by me right now?

- It's time to try taking contrary actions. To catch the impulse as it's coming over us, take a deep breath, and .. do the opposite.  We call this "acting as if."  When we'd normally have a judgemental reaction to something, we try to be accepting instead. When we feel anger rising inside, we strive to stay calm.   When we're about to give in to some old self-centered impulse, we ask instead how we might be of service.

- Acting as if our HP has removed our defects and provided the assets we need, we grow more and more confident.  Soon we're able to gracefully stick the landing.

- Perhaps the biggest obstacle to our freedom -- greater than any character defect -- is fear.

- Most of our day-to-day fears, through, are really not so helpful.  We're convinced we will fail at our job.  We're too anxious to go out on dates.  We're terrified that some financial catastrophe or unforeseen malady is just around the corner.

- That's what FEAR is, they said, False Evidence Appearing Real.

- If we're doing nighty meditation, we might ask then if any fears have gotten the better of us. Did anything today trigger our old anxieties -- about money, our reputation, our love life?

- One way to bring this home is to note our successes along with our stumbles. What challenges did we successfully meet today? How are we doing with opportunities?  Are we standing up for ourselves, taking a chance with a new acquantance or job?  A wise fellow likes to say, "Fear is just excitment without the breath.  So take a breath and get excited!"  We ask ourvselves:  What happened today that was new and exciting?

- To help us become entirely ready to let go of our character defects, we might spend some time looking at our list and meditatig on how those old strategies are no longer useful -- how they no longer serve us -- and how we're learning to take better actions.

** Step 7
- Identifying our fears and character defects and then learning to take contrary actions instead of succumbing to our worst instincts is hard work.  We will often fall short of the ideals we're cultivating.

- We cannot completely remove our shortcomings without help.  Thats' where Step Seven comes in.

- Learning /humility/ is something else entirely: getting a clear, unvarnished view of ourselves.  Humility is a previous attribute we strive to cultivate, the antidoe to the self-destructive grandiosity or toxic self-loathing that fueled our using.  If we can accept, without shame, our good and bad sides, we can really begin to grow.

- We humbly ask our HP to do what we cannot -- remove any obstacles to being connected and useful and happy.

- Big Book Step 7
  #+begin_quote
  My Creator, I am now willing that you should have all of me, good and bad. I pray that you now remove from me every single defect of character which stands in the way of my usefulnes to you and my fellows.  Grant me strength, as I go out from here, to do your bidding.
  #+end_quote

- Like most of the steps, in other words, Seven isn't a one-time deal.  Recognizing how hard it will be on a given day to take the next right action, many of us start our morning with a few minutes of meditation or we say a short prayer to this effect
  #+begin_quote
  Today, help me set asside the defectws of character that block my recovery. Help me take action that will serve me, those around me, and the universe better.
  #+end_quote

- But may also here this mind-bending: "God is a verb".  Our spirituality in recovery isn't passive. We find our HP in the action we take; every time we do the next right hting, we're building up our connection with it.  Cultivating willingness and humility, we're putting ourselves in the path of grace and  making ourselves available to enjoy all the luck the unvierse can offer.

- Every one of us is a blank canvas.  We have no ideas who we might someday be and what we might achiieve.   But for the firt time, not knowing what might be coming in the future doesn't terrify us.

  
** Step 8
- The overtures we're contemplating may be a snap, bringing us emotion catharsis and relief, or they may be quite difficult.  How secure are we that we can handle any upset or disappointment?
- That's why compiling our list of amends and becoming willing to make them is a Step in itself.  We do Step Eigth as if there is no Step Nine at all.
- And then there are those people who don't even know we lied to them, stole from them, cheated on them.  They're perfectly happy not knowing;  do we really have to upset them -- and more important, ourselves -- with a terrible truth they probably don't want to hear?   For now, we just put their names on our list.  Whether or not we will make amends and how we'll do it area questions for another day.

** Step 9
- Whenever possible, we make an amends face to face.
- What we need to do is usually pretty obvious.  But even then, we're careful to follow our sponsor's guidance.  They can -- and will -- recommend good, specific ways to make an amends that takes into account our whole situation.
- Apologizing for what happened is only the beginning.
- Instead of focusing on events, we focus on behaviors:  "I'm so sorry I lash out at you and call you nasty things. I'm learning to do better."
- In Step Nine, we aren't rationalizing our past behavior, we are mending the damage we caused.  That we're able to do so it the best evidence we have of how profoundly we've changed.
- In fact, once we've said our peace, we should ask if we've left anthing out.  ... We must let the person we've wounded express their feelings on their own terms.  If they're carrying around a painful burdeen, we have an opprotunity to help them put it down.
- If someone refuses to communicate with us at all, we must respect that, but we might instead volunteer for a charity that aligns with their world view.  And if someone has died, we will need to find some other way to repair any damage.  Rituals, prayers, and medication can be lovely, but we can honor a lost friend or parent even more concretely by taking part in activities they relished and giving back to people they loved.
- For these "not yets" we get to work anywya by making what's called a living amends.
- If we were sexually compulsive, we may well have passed on STIs to countless strangers. In recovery honesty is a cornerstone of our sexual ideal; we take care of ourselves and take care to take care of others too.
- If we became dealers in active addiction, or coaked people in our circle to try new drugs or take other risks, we can make one obvious living amends -- not to sell crystal meth or other drugs  We might also make ourselves available to help former contacts find recovery if they need it.
- If we've been unfaithful to our partner, an itemized shcedule of infidelities might cripple their self-esteem.  We've been carrying around a heavy burden, but no matter how desperataly we want to put it down, getting whatever it is off our chest isn't always the right thing to do.
  
** Step 10
- The cure isn't onerous -- we just have to write it out, identify our part in the problem and then take whatever action is needed.
- So this step is critical.  We cannot be present if we're stuck in our fears and resentments.  And we won't stay sober if we can't be present.  ... Doing Step Ten clears out our spirit, making us available for whatever surprise today holds.
- Spiritual checkins
  - Did I stay sober?
  - Did I connect with people?
  - Did I run on my willpower or was I able to surrender control?
  - Did I react to people or situations out of resentment or fear?
  - Did I hold myself accountable to anyone?
  - Did I remember to be gentle on myself when I fell into old habits?
  - Did I do something that was hard for me?
  - Did I forgive anyone?
  - Did I apologize to anyone and clean up any messes?
  - Did I show up for myself and take care of my business?
  - Did I stay in touch with my HP?
  - Did I help anyone today?
   

    
** Step 11

** Step 12
